version: '3.7'
services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - '3306:3306'
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./data:/var/lib/mysql
